import SwiftUI

/// Nectar grocery design tokens — primary green from the product UI.
enum NectarColors {
    static let brand = Color(hex: 0x53B175)
    static let brandSoft = Color(hex: 0xEBF8F0)
    static let navy = Color(hex: 0x181725)
    static let navySoft = Color(hex: 0x2E2C3A)
    static let teal = Color(hex: 0x53B175)
    static let tealSoft = Color(hex: 0xEBF8F0)
    static let background = Color(hex: 0xF2F2F2)
    static let surface = Color.white
    static let textPrimary = Color(hex: 0x292D32)
    static let textSecondary = Color(hex: 0x9FA1A3)
    static let danger = Color(hex: 0xF71818)
    static let success = Color(hex: 0x0FCB67)
    static let warning = Color(hex: 0xD97706)
    static let border = Color(hex: 0xE5E7EB)
    static let cardGold = Color(hex: 0xC9A227)
    static let inputBackground = Color(hex: 0xF7F8FA)
    static let green = Color(hex: 0x53B175)
    static let googleBlue = Color(hex: 0x5383EC)
    static let facebookBlue = Color(hex: 0x4A66AC)
    static let white = Color(hex: 0xFFFFFF)
    static let black = Color(hex: 0x000000)
    static let gray = Color(hex: 0x9FA1A3)
    static let graySoft = Color(hex: 0xE5E7EB)
    static let grayDark = Color(hex: 0x111827)
    static let grayLight = Color(hex: 0xF3F4F6)
    static let grayXLight = Color(hex: 0xF9FAFB)
    static let grayXXLight = Color(hex: 0xFCFCFD)
    static let grayXXXLight = Color(hex: 0xFEFEFE)
    static let grayXXXXLight = Color(hex: 0xFFFFFF)
    static let blue = Color(hex: 0x5383EC)
    static let blueDark = Color(hex: 0x0D3892)
    static let blueSoft = Color(hex: 0xEBF8F0)
    static let blueLight = Color(hex: 0xF3F4F6)
    static let blueXLight = Color(hex: 0xF9FAFB)
    static let blueXXLight = Color(hex: 0xFCFCFD)
    static let blueXXXLight = Color(hex: 0xFEFEFE)
    static let blueXXXXLight = Color(hex: 0xFFFFFF)
    static let purple = Color(hex: 0x8B5CF6)
    static let purpleSoft = Color(hex: 0xEBF8F0)
    static let purpleDark = Color(hex: 0x111827)
    static let purpleLight = Color(hex: 0xF3F4F6)
    static let purpleXLight = Color(hex: 0xF9FAFB)
    static let purpleXXLight = Color(hex: 0xFCFCFD)
    static let purpleXXXLight = Color(hex: 0xFEFEFE)
    static let purpleXXXXLight = Color(hex: 0xFFFFFF)
    static let orange = Color(hex: 0xF59E0B)
    static let orangeSoft = Color(hex: 0xEBF8F0)
    static let orangeDark = Color(hex: 0x111827)
    static let orangeLight = Color(hex: 0xF3F4F6)
    static let orangeXLight = Color(hex: 0xF9FAFB)
    static let orangeXXLight = Color(hex: 0xFCFCFD)
    static let orangeXXXLight = Color(hex: 0xFEFEFE)
    static let orangeXXXXLight = Color(hex: 0xFFFFFF)
    static let pink = Color(hex: 0xEC4899)
    static let pinkSoft = Color(hex: 0xEBF8F0)
    static let pinkDark = Color(hex: 0x111827)
    static let pinkLight = Color(hex: 0xF3F4F6)
    static let pinkXLight = Color(hex: 0xF9FAFB)
    static let pinkXXLight = Color(hex: 0xFCFCFD)
    static let pinkXXXLight = Color(hex: 0xFEFEFE)
    static let pinkXXXXLight = Color(hex: 0xFFFFFF)
    static let red = Color(hex: 0xEF4444)
    static let redSoft = Color(hex: 0xEBF8F0)
    static let redDark = Color(hex: 0x111827)
    static let redLight = Color(hex: 0xF3F4F6)
    static let redXLight = Color(hex: 0xF9FAFB)
    static let redXXLight = Color(hex: 0xFCFCFD)
    static let redXXXLight = Color(hex: 0xFEFEFE)
    static let redXXXXLight = Color(hex: 0xFFFFFF)
    static let yellow = Color(hex: 0xF59E0B)
    static let yellowSoft = Color(hex: 0xEBF8F0)
    static let yellowDark = Color(hex: 0x111827)
    static let yellowLight = Color(hex: 0xF3F4F6)
    static let yellowXLight = Color(hex: 0xF9FAFB)
    static let yellowXXLight = Color(hex: 0xFCFCFD)
    static let yellowXXXLight = Color(hex: 0xFEFEFE)
    static let yellowXXXXLight = Color(hex: 0xFFFFFF)
    static let brown = Color(hex: 0x92400E)
    static let brownSoft = Color(hex: 0xEBF8F0)
    static let brownDark = Color(hex: 0x111827)
    static let brownLight = Color(hex: 0xF3F4F6)
    static let brownXLight = Color(hex: 0xF9FAFB)
    static let brownXXLight = Color(hex: 0xFCFCFD)
    static let brownXXXLight = Color(hex: 0xFEFEFE)
    static let brownXXXXLight = Color(hex: 0xFFFFFF)
    static let whiteLight = Color(hex: 0xF3F4F6)
    static let whiteXLight = Color(hex: 0xF9FAFB)
    static let whiteXXLight = Color(hex: 0xFCFCFD)
    static let whiteXXXLight = Color(hex: 0xFEFEFE)
    static let whiteXXXXLight = Color(hex: 0xFFFFFF)
}

extension Color {
    init(hex: UInt, alpha: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: alpha
        )
    }
}
